server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
              filters:
                - RemoveRequestHeader=Origin

            - id: main-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/**
              filters:
                - RemoveRequestHeader=Origin

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns:
                  - "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
